name: Packaging

on:
  - push

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.11"
          
      - name: Install tox
        run: python -m pip install tox
      - name: Run black
        run: tox -e format

  typing:
    name: Check typing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.11"
          
      - name: Install tox
        run: python -m pip install tox
      - name: Run mypy
        run: tox -e type
  
  linter:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.11"
          
      - name: Install tox
        run: python -m pip install tox
      - name: Run ruff
        run: tox -e linter

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.11"
            toxenv: "py311"
          - version: "3.10"
            toxenv: "py310"
          - version: "3.9"
            toxenv: "py39"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: ${{ matrix.python.version }}
      - name: Install tox
        run: python -m pip install tox
      - name: Run pytest
        run: tox -e ${{ matrix.python.toxenv }}

  build:
    name: Build source distribution and Linux wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.11"

      - name: Install build
        run: python -m pip install build

      - name: Run build
        run: python -m build

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*